services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}         
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}       
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: chat-bot-app
    environment:
      TG_TOKEN: ${TG_TOKEN}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} 
      FILE_PATH: ${FILE_PATH}
    depends_on:
      - db 
    ports:
      - "8000:8000" 

volumes:
  postgres_data: